name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: 8.7
      - run: ./gradlew checkstyleMain
      - run: ./gradlew test jacocoTestReport
      - run: ./gradlew test
          arguments: build
          build-root-directory: app
       - name: Publish code coverage
         uses: paambaati/codeclimate-action@v9.0.0
         env:
           HEXLET_ID: ${{secrets.HEXLET_ID}}
           JACOCO_SOURCE_PATH: app/src/main/java
         with:
           coverageCommand: ./gradlew test jacocoTestReport
           coverageCommand: make report
           coverageLocations: ${{github.workspace}}app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
